apiVersion: v1
kind: Pod
metadata:
  name: ipc-python
spec:
  volumes:
  - name: {{ .Values.volume.name }}
    emptyDir: {}
  containers: 
  - name: producer
    image: tstipa/ipc-test-python
    command: ["python3"]
    args: ["/app/ipc-test.py", "--producer", "--num_messages", {{ .Values.producer.numMessages | quote }}]
    volumeMounts:
    - name: {{ .Values.volume.name }}        
      mountPath: /ipc_test
  - name: consumer
    image: tstipa/ipc-test-python
    command: ["python3"]
    args: ["/app/ipc-test.py", "--consumer"]
    volumeMounts:
    - name: {{ .Values.volume.name }}
      mountPath: {{ .Values.volume.mountPath }}
  restartPolicy: Never  
