apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipc-test-python-deployment
  labels:
    app: ipc-test-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipc-test-python
  template:
    metadata:
      labels:
        app: ipc-test-python
    spec:
      volumes:
      - name: shared-socket
        emptyDir: {}
      containers: 
      - name: producer
        image: tstipa/ipc-test-python
        command: ['python3']
        args: ['/app/ipc-test.py', '--producer', '--num_messages', '10']
        volumeMounts:
        - name: shared-socket        
          mountPath: /ipc_test
      - name: consumer
        image: tstipa/ipc-test-python
        command: ['python3']
        args: ['/app/ipc-test.py', '--consumer']
        volumeMounts:
        - name: shared-socket        
          mountPath: /ipc_test
