apiVersion: v1
kind: Pod
metadata:
  name: ipc-c
spec:
  containers:
  - name: producer
    image: tstipa/ipc_test
    command: ['./ipc', '-producer']
  - name: consumer
    image: tstipa/ipc_test
    command: ['./ipc', '-consumer']
  restartPolicy: Never  
